---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php for Ubuntu servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest 
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install httpd and php for REDOS servers
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "REDOS"
